version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    allow:
      - dependency-type: 'direct'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
