// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
    "title": "Useful Dev Tools",
    "sidebar": {
        "appName": "Useful Dev Tools",
        "navigation": "Navigation",
        "welcome": "Welcome to Useful Dev Tools"
    },
    "notFound": {
        "title": "404",
        "subtitle": "Page Not Found",
        "description": "The page you are looking for does not exist.",
        "returnHome": "Return Home"
    },
    "footer": {
        "github": "View on GitHub",
        "coffee": "Buy me a coffee",
        "copyright": "Copyright © {year} Nico Möhn"
    },
    "pages": {
        "home": "Home",
        "uuid": "UUID Generator",
        "regex": "Regex Tester",
        "jwt": "JWT Decoder",
        "hash": "Hash Generator",
        "urlEncoder": "URL Encoder/Decoder",
        "markdown": "Markdown Converter",
        "csv": "CSV/JSON Converter",
        "base64": "Base64 Converter"
    },
    "home": {
        "title": "Useful Developer Tools",
        "description": "A set of useful, client-side tools for developers.",
        "search": {
            "placeholder": "Search tools...",
            "noResults": "No tools found matching your search"
        },
        "filters": {
            "all": "All Tools",
            "cryptography": "Cryptography",
            "generators": "Generators",
            "testing": "Testing",
            "converters": "Converters"
        }
    },
    "themeToggle": {
        "toggleTheme": "Toggle Theme"
    },
    "tools": {
        "uuid": {
            "title": "UUID Generator",
            "description": "Generate UUIDs in different versions",
            "generateSingle": "Generate UUID",
            "generatedUuids": "Generated UUID",
            "selectVersion": "Select UUID version",
            "versions": {
                "v1": "Version 1 (Time-based)",
                "v4": "Version 4 (Random)",
                "v6": "Version 6 (Reordered time)",
                "v7": "Version 7 (Unix timestamp)"
            }
        },
        "regex": {
            "title": "Regex Validator",
            "description": "Test regular expressions",
            "regexPattern": "Regex Pattern",
            "testString": "Test String",
            "validRegex": "Valid",
            "invalidRegex": "Invalid",
            "regexPlaceholder": "^[a-zA-Z0-9]+$",
            "testStringPlaceholder": "Enter text to test against regex",
            "testNoMatch": "No match",
            "fullMatch": "Full match",
            "partialMatch": "Partial match",
            "noTestString": "No test string provided",
            "matchingCharacters": "Matching characters",
            "nonMatchingCharacters": "Non-matching characters"
        },
        "hash": {
            "title": "Hash Generator",
            "description": "Generate cryptographic hashes",
            "inputText": "Input Text",
            "selectAlgorithm": "Select hash algorithm",
            "inputPlaceholder": "Enter text to hash",
            "generateHash": "Generate Hash",
            "generating": "Generating...",
            "result": "Hash Result",
            "algorithms": {
                "md5": "MD5",
                "sha256": "SHA-256",
                "sha512": "SHA-512",
                "bcrypt": "bcrypt",
                "xxhash": "xxHash"
            }
        },
        "csv": {
            "title": "CSV-JSON Converter",
            "description": "Convert between CSV and JSON",
            "mode": "Conversion Mode",
            "csvToJson": "CSV to JSON",
            "jsonToCsv": "JSON to CSV",
            "input": "Input",
            "output": "Result",
            "convert": "Convert",
            "clear": "Clear",
            "copyOutput": "Copy Result",
            "downloadFile": "Download File",
            "uploadFile": "Drop a file here or click to upload",
            "inputPlaceholder": "Paste your data here...",
            "fileInfo": "File: {{fileName}} ({{fileSize}})",
            "options": "Options",
            "hasHeader": "First row is header",
            "prettyPrint": "Pretty print JSON"
        },
        "base64": {
            "title": "Base64 Converter",
            "description": "Encode and decode Base64",
            "inputText": "Input Text",
            "outputText": "Result",
            "mode": "Mode",
            "inputType": "Input Type",
            "encodePlaceholder": "Enter text to encode to Base64",
            "decodePlaceholder": "Enter Base64 text to decode",
            "clearAll": "Clear All",
            "downloadFile": "Download as File",
            "uploadFile": "Upload File",
            "dropFile": "Drop a file here or click to browse",
            "fileInfo": "File: {name} ({size})",
            "supportedFormats": "Supports images, PDFs, text files, and more",
            "output": {
                "fileEncoded": "File Encoded",
                "fileConverted": "File converted to Base64",
                "base64Output": "Base64 output ({count} characters)",
                "outputTruncated": "Result truncated for display. Use copy or download to get the full content.",
                "copyToClipboard": "Copy to clipboard",
                "readyForDownload": "Ready for Download",
                "decodedFileReady": "Decoded file is ready. Click \"Download as File\" to save it."
            },
            "modes": {
                "encode": "Encode to Base64",
                "decode": "Decode from Base64"
            },
            "inputTypes": {
                "text": "Text Input",
                "file": "File Upload"
            },
            "errors": {
                "fileTooBig": "File is too large (max 10MB)",
                "fileReadError": "Error reading file",
                "invalidBase64File": "Invalid Base64 data for file conversion"
            }
        },
        "markdown": {
            "title": "Markdown-HTML Converter",
            "description": "Convert between Markdown and HTML",
            "markdownInput": "Markdown Input",
            "htmlOutput": "HTML Result",
            "markdownPlaceholder": "Enter your markdown here...",
            "htmlPlaceholder": "Enter your HTML here...",
            "preview": "Preview",
            "copyMarkdown": "Copy Markdown",
            "copyHtml": "Copy HTML",
            "copiedToClipboard": "Copied to clipboard!",
            "clearAll": "Clear All",
            "conversionMode": "Conversion Mode",
            "markdownToHtml": "Markdown to HTML",
            "htmlToMarkdown": "HTML to Markdown"
        },
        "urlEncoder": {
            "title": "URL Encoder",
            "description": "Encode and decode URLs",
            "input": "Input",
            "output": "Result",
            "mode": "Mode",
            "clearAll": "Clear All",
            "valid": "Valid",
            "invalid": "Invalid",
            "useComponentEncoding": "Component encoding",
            "modes": {
                "encode": "Encode",
                "decode": "Decode"
            },
            "inputPlaceholder": {
                "encode": "Enter text to URL encode",
                "decode": "Enter URL encoded text to decode"
            },
            "outputPlaceholder": "Result will appear here"
        }
    },
    "fileUpload": {
        "dropFile": "Drop a file here or click to browse",
        "fileInfo": {
            "name": "Name",
            "size": "Size",
            "type": "Type",
            "lastModified": "Last Modified",
            "unknown": "Unknown"
        },
        "fileSizes": {
            "bytes": "Bytes",
            "kb": "KB",
            "mb": "MB",
            "gb": "GB"
        }
    }
};
export default messages;